spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jiangjiabin001.top:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: bb357159
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.bingo: debug
  file: log/blog-dev.log



